---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: false
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.py"
  - "**.rb"
exclude_paths:
  - app/grandchallenge/core/static/**/*
  - app/grandchallenge/**/migrations/**/*
  - app/tests/core_tests/resources/**/*
