language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  coverage run --source=django manage.py test comicsite
after_success:
  coveralls
