language: python
python:
  - "2.7"
addons:
  mariadb: 10.1
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  coverage run --source=django django/manage.py test
after_success:
  coveralls
