language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  coverage run --source=django django/manage.py test comicsite contenttypes sessions messages sites comicmodels profiles django_dropbox
after_success:
  coveralls
