language: python
python:
  - 2.7
addons:
  mariadb: 10.1
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - echo "[client]" > $HOME/.my.cnf
  - echo "default-character-set = utf8" >> $HOME/.my.cnf
  - echo "[mysqld]" >> $HOME/.my.cnf
  - echo "character-set-server = utf8" >> $HOME/.my.cnf
  - echo "collation-server = utf8_general_ci" >> $HOME/.my.cnf
  - mysql -u root --password= -e "CREATE DATABASE comic;"
script:
  cd django && coverage run --source='.' manage.py test
after_success:
  coveralls
