sudo: required
services:
  - docker
language: python
python:
  - 2.7
before_install:
  - docker-compose up --build -d
  - docker-compose run web pip install coveralls
script:
  - docker-compose run web dockerize -wait tcp://db:3306 -timeout 120s bash -c "coverage run --source='.' manage.py test"
after_script:
  - docker-compose run web coveralls
  - docker-compose down
