language: python
python:
  - 2.7
addons:
  mariadb: 10.1
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - cp testing/60-mariadb.cnf $HOME/.my.cnf
  - mysql -u root --password= -e "CREATE DATABASE comic;"
script:
  cd django && coverage run --source='.' manage.py test
after_success:
  coveralls
