sudo: required

services:
  - docker

language: python

python:
  - 3.6

env:
  DOCKER_COMPOSE_VERSION: 1.15.0

before_install:
  - sudo apt-get update
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - pip install codecov pytest-cov

install:
  - docker-compose up --build -d

script:
  - docker-compose run web dockerize -wait tcp://db:3306 -timeout 30s bash -c "py.test --cov-report= --cov=."; mv app/.coverage .coverage.docker; exit $(docker inspect -f '{{.State.ExitCode}}' $(docker ps -aqf name=comicdjango_web_run_1))
  - pytest --ignore=app --cov-report= --cov=.

after_success:
  - coverage combine
  - codecov

after_script:
  - docker ps -aqf name=comicdjango_web_run_1
