sudo: required
services:
  - docker
language: python
python:
  - 2.7
install:
  - docker-compose up --build -d
script: >-
  docker-compose run web dockerize -wait tcp://db:3306 -timeout 120s
  bash -c "
  python manage.py test
  "
after_script:
  - docker-compose down
