version: '2'

services:

  db:
    image: mariadb:10.1
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
     - MYSQL_DATABASE=comic
    restart: always

  web:
    extends:
      file: docker-compose.common.yml
      service: web
    links:
      - db:mysql
      - memcached
    depends_on:
      - db
      - memcached
      - dropbox
    volumes:
      - static:/static/
    volumes_from:
      - dropbox

  http:
    extends:
      file: docker-compose.common.yml
      service: http
    ports:
      - "8000:80"
    links:
      - web
    depends_on:
      - web
    volumes:
      - static:/srv/static/:ro

  memcached:
    extends:
      file: docker-compose.common.yml
      service: memcached

  dropbox:
    extends:
      file: docker-compose.common.yml
      service: dropbox

volumes:
  static:
