version: '2'

services:

  web:
    build:
      context: .
      dockerfile: ./dockerfiles/web/Dockerfile
    environment:
      - GOOGLE_ANALYTICS_TRACKING_ID=UA-XXXXX-Y
    command: >-
      dockerize -wait tcp://db:3306 -timeout 120s bash -c "
      python manage.py collectstatic --noinput
      && envsubst < /tmp/google-analytics-tracking.js.template > /static/js/google-analytics-tracking.js
      && python manage.py migrate
      && python manage.py loaddata comic_initial_project user_everyone
      && python manage.py check_permissions
      && gunicorn -b 0.0.0.0 comic.wsgi
      "
    restart: always

  http:
    build: ./dockerfiles/http
    environment:
      - SERVER_NAME=localhost
      - SENDFILE_STATUS=off
    command: >-
      bash -c "envsubst '$$SERVER_NAME $$SENDFILE_STATUS' < /tmp/nginx.conf.template > /etc/nginx/nginx.conf
      && openssl req -x509 -newkey rsa:4096 -keyout /etc/ssl/private/$$SERVER_NAME.key -out /etc/ssl/certs/$$SERVER_NAME.crt -days 365 -nodes -subj '/CN=$$SERVER_NAME'
      && nginx -g 'daemon off;'"
    restart: always

  memcached:
    image: memcached:1.4
    restart: always

  dropbox:
    image: janeczku/dropbox
    volumes:
      - /srv/public/Dropbox/:/dbox/Dropbox/
    restart: always
