version: '2.3'

services:
  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_USER: comic
      POSTGRES_DB: comic
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "comic"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "./postgres_data:/var/lib/postgresql/data/"


volumes:
  static:
  media:
