version: '2'

services:

  db:
    image: mariadb:10.1
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
     - MYSQL_DATABASE=comic
    restart: always

  web:
    extends:
      file: docker-compose.common.yml
      service: web
    links:
      - db:mysql
      - memcached
    depends_on:
      - db
      - memcached
      - dropbox
      - celery_worker
    volumes:
      - static:/static/
      - ./app:/app/
      # The docker socket is only needed for testing
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - dropbox

  http:
    extends:
      file: docker-compose.common.yml
      service: http
    ports:
      - "80:80"
      - "443:443"
    links:
      - web
    depends_on:
      - web
    volumes:
      - static:/srv/public/static/:ro
      - ssl_certs:/etc/ssl/certs/
      - ssl_private:/etc/ssl/private/

  memcached:
    extends:
      file: docker-compose.common.yml
      service: memcached

  dropbox:
    extends:
      file: docker-compose.common.yml
      service: dropbox

  registry:
    extends:
      file: docker-compose.common.yml
      service: registry
    ports:
      - "5000:5000"
    volumes:
      - ssl_certs:/etc/ssl/certs/:ro
      - ssl_private:/etc/ssl/private/:ro
      - ./tests/auth:/auth/

  rabbitmq:
    extends:
      file: docker-compose.common.yml
      service: rabbitmq
    ports:
      - "8080:15672"

  celery_worker:
    extends:
      file: docker-compose.common.yml
      service: web
    command: celery -A comic worker -l info
    links:
      - db:mysql
      - rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - ./app:/app/
      - /var/run/docker.sock:/var/run/docker.sock

  celery_beat:
    extends:
      file: docker-compose.common.yml
      service: web
    command: celery -A comic beat -l info
    links:
      - db:mysql
      - rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - ./app:/app/

  flower:
    image: crgwbr/docker-celery-flower
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
    ports:
      - "5555:5555"
    links:
      - rabbitmq
    restart: always


volumes:
  static:
  ssl_certs:
  ssl_private:
