version: '2.3'

services:

  web:
    build:
      context: .
      dockerfile: ./dockerfiles/web/Dockerfile
    environment:
      - GOOGLE_ANALYTICS_ID=UA-XXXXX-Y
    command: >-
      dockerize -wait tcp://postgres:5432 -timeout 120s bash -c "
      [ -e /static ] || rm -rf /static
      && python manage.py collectstatic --noinput
      && mkdir -p /dbox/Dropbox/media/
      && python manage.py migrate
      && python manage.py check_permissions
      && python manage.py initcomicdemo
      && gunicorn -b 0.0.0.0 config.wsgi
      "
    restart: always

  http:
    build: ./dockerfiles/http
    environment:
      - SERVER_NAME=localhost
      - SENDFILE_STATUS=off
    command: >-
      bash -c "envsubst '$$SERVER_NAME $$SENDFILE_STATUS' < /tmp/nginx.conf.template > /etc/nginx/nginx.conf
      && openssl req -x509 -newkey rsa:4096 -keyout /etc/ssl/private/$$SERVER_NAME.key -out /etc/ssl/certs/$$SERVER_NAME.crt -days 365 -nodes -subj '/CN=$$SERVER_NAME'
      && nginx -g 'daemon off;'"
    restart: always

  memcached:
    image: memcached:1.4
    restart: always

  redis:
    image: redis:4.0
    command: redis-server --appendonly yes
    restart: always
